# This file was generated by GoReleaser. DO NOT EDIT.
cask "rn-events" do
  version "2.0.7"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Darwin_x86_64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
      sha256 "1d1cacaef5fbdec5297a43f9ae343e8d8ee676646c29820cf42fc978397459f2"
    end
    on_arm do
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Darwin_arm64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
      sha256 "a16391f7872c8270438874b5e0ab14ddc8b0bcf0dfc443a4705babb0012e264f"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Linux_x86_64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
      sha256 "e33635eaf0c6b6abad306f90d7d970fe28e7a1c3b0f26ef1f34a4c30d4a07854"
    end
    on_arm do
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Linux_arm64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
      sha256 "d320e43e3c2bbb8a081b5b597b8b625a37eafa19787af9c3b72b91e1b9a346f9"
    end
  end

  name "rn-events"
  desc "RetailNext events CLI"
  homepage "https://retailnext.net/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rn-events"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rn-events"]
    end
  end

  # No zap stanza required

end
