# This file was generated by GoReleaser. DO NOT EDIT.
cask "rn-events" do
  version "2.2.1"

  on_macos do
    on_intel do
      sha256 "bf98a4ec31c27f311d936b2efa5ce619cd38d80c1debd659935fd6c72516c563"
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Darwin_x86_64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
    end
    on_arm do
      sha256 "139f9d601537b81ce50a5a3d743fa879230baf88073bf41b4c11702f48d1fcf7"
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Darwin_arm64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
    end
  end

  on_linux do
    on_intel do
      sha256 "966c4602889b716646084841043bfe6df2fc270f351c06989044cea6fabfca33"
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Linux_x86_64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
    end
    on_arm do
      sha256 "4b0687e15d511ab65f758d7365877faf7d30cc9b7ab36725e129694baf3cf559"
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Linux_arm64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
    end
  end

  name "rn-events"
  desc "RetailNext events CLI"
  homepage "https://retailnext.net/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rn-events"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rn-events"]
    end
  end

  # No zap stanza required

end
