# This file was generated by GoReleaser. DO NOT EDIT.
cask "rn-events" do
  version "2.1.0"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Darwin_x86_64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
      sha256 "d8472ec3cc651471732a868b4b7272836f06de5e653de38769faad9267861e72"
    end
    on_arm do
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Darwin_arm64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
      sha256 "e6c8b0484535135f3ca3bc743dcb4d3d26b97751a5174414d15e69d263b49d2e"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Linux_x86_64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
      sha256 "ffd7ac7e641d794f4e4ce01d04acf863585eaadba802303a33e5e67a93f12409"
    end
    on_arm do
      url "https://storage.googleapis.com/rn-events-72daf14f/v#{version}/rn-events_Linux_arm64.tar.gz",
        verified: "storage.googleapis.com/rn-events-72daf14f/"
      sha256 "82210a4b2f6ae539c85dc0e2cc14d26404fa022bba0d66a3ddf7e404ba8c9f05"
    end
  end

  name "rn-events"
  desc "RetailNext events CLI"
  homepage "https://retailnext.net/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rn-events"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rn-events"]
    end
  end

  # No zap stanza required

end
