name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  ci:
    name: Audit casks
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Check out repository
        uses: actions/checkout@v4

      - name: brew style
        run: brew style --casks Casks/

      - name: brew audit
        run: brew audit --cask --online Casks/rn-events.rb
